## Initial Exploratory Data Analysis and Variable Creation
### Elizabeth Greenan

In [1]:
# Import packages
import pandas as pd

In [6]:
# Read CSV file in
e_cig_data = pd.read_csv("../data/LLCP2024.csv")
e_cig_data.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
0,1,2,2282024,2.0,28.0,2024,1100,2024000001,2024000001,1.0,...,NaN,9.0,2,0.0,1,0,1,1.0,2.0,2.0
1,1,2,2212024,2.0,21.0,2024,1100,2024000002,2024000002,1.0,...,4.0,9.0,2,0.0,1,0,1,1.0,1.0,2.0
2,1,2,2212024,2.0,21.0,2024,1100,2024000003,2024000003,1.0,...,4.0,2.0,1,100.0,2,1400,1,NaN,NaN,2.0
3,1,2,2282024,2.0,28.0,2024,1100,2024000004,2024000004,1.0,...,NaN,9.0,2,0.0,1,0,1,1.0,1.0,2.0
4,1,2,2212024,2.0,21.0,2024,1100,2024000005,2024000005,1.0,...,3.0,9.0,2,0.0,1,0,1,NaN,NaN,2.0

In [8]:
# Look at dimensions of dataset
e_cig_data.shape

(457670, 301)

In [10]:
# Use describe funtion to look at general statistics of dataset
e_cig_data.describe()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_LCSCTSN,_LCSPSTF,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK3,_RFDRHV9,_FLSHOT7,_PNEUMO3,_AIDTST4
count,457670.000000,457670.000000,4.576700e+05,457669.000000,457669.000000,457670.000000,457670.000000,4.576700e+05,4.576700e+05,81730.0,...,393433.000000,406226.000000,457670.000000,457669.000000,457670.000000,457670.000000,457670.000000,179344.000000,179344.000000,414178.000000
mean,30.823537,6.426995,6.801723e+06,6.644815,15.489804,2024.042723,1118.669784,2.024007e+09,2.024007e+09,1.0,...,3.420252,8.468687,2.196764,100.059875,1.948965,10443.929019,1.869063,2.336850,2.462223,1.999684
std,15.939364,3.356938,3.316166e+06,3.316101,8.664519,0.202232,38.966920,7.488291e+03,7.488291e+03,0.0,...,0.792956,1.892208,2.226566,261.371685,2.418721,30166.526771,2.414067,2.602255,2.814818,1.665037
min,1.000000,1.000000,2.024000e+03,1.000000,1.000000,2024.000000,1100.000000,2.024000e+09,2.024000e+09,1.0,...,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,18.000000,4.000000,4.112024e+06,4.000000,8.000000,2024.000000,1100.000000,2.024002e+09,2.024002e+09,1.0,...,3.000000,9.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000
50%,31.000000,7.000000,7.052024e+06,7.000000,15.000000,2024.000000,1100.000000,2.024005e+09,2.024005e+09,1.0,...,4.000000,9.000000,2.000000,3.000000,1.000000,47.000000,1.000000,1.000000,1.000000,2.000000
75%,44.000000,9.000000,9.302024e+06,9.000000,23.000000,2024.000000,1100.000000,2.024008e+09,2.024008e+09,1.0,...,4.000000,9.000000,2.000000,29.000000,1.000000,467.000000,1.000000,2.000000,2.000000,2.000000
max,78.000000,12.000000,1.231202e+07,12.000000,31.000000,2025.000000,1200.000000,2.024044e+09,2.024044e+09,1.0,...,4.000000,9.000000,9.000000,900.000000,9.000000,99900.000000,9.000000,9.000000,9.000000,9.000000

In [11]:
# Look at the number of unique years in the dataset. I was surprised to see 2025 in it
e_cig_data["IYEAR"].unique()

array([2024, 2025])

In [12]:
# Look at the counts of unique years in the dataset, because I was surprised to see 2025 in the 2024 dataset
e_cig_data["IYEAR"].value_counts()

IYEAR
2024    438117
2025     19553
Name: count, dtype: int64

In [35]:
# Create a list of the initial variables we think we want to keep (these are coming directly from the Data Dictionary)
intitial_cig_data_variables = ["_AGEG5YR", "ALCDAY4", "AVEDRNK4", "BLIND", "_BMI5", "_BMI5CAT", "CHECKUP1", "CHILDREN", "CVDCRHD4", "DEAF", "DECIDE", "_DENVST3", "DIABETE4", "DIFFALON", "DIFFDRES", "DIFFWALK", "ECIGNOW3", "EDUCA", "EMTSUPRT", "EXERANY2", "GENHLTH", "_HLTHPL2", "INCOME3", "LASTSMK2", "LCSSCNCR", "_LCSAGE", "_LCSCTSN", "LCSLAST_", "LCSNUMC_", "_LCSYSMK", "_LCSSMKG", "_LCSYQTS", "LSATISFY", "MARIJAN1", "MARITAL", "MEDCOST1", "MENTCIGS", "MENTECIG", "_MENT14D", "MENTHLTH", "_PACKDAY", "_PACKYRS", "_PHYS14D", "PHYSHLTH", "POORHLTH", "PREDIAB2", "_RACE", "_RFBMI5", "_RFHLTH", "_RFSMOK3", "SEXVAR", "SDHBILLS", "SDLONELY", "SMOKE100", "SMOKDAY2", "_SMOKER3", "SSBSUGR2", "SSBFRUT3", "STOPSMK2", "_TOTINDA", "USENOW3", "_CURECI3"]

In [36]:
# Create a new dataframe for these initial variables
filtered_e_cig_data = e_cig_data[intitial_cig_data_variables]

In [37]:
# Show the first 5 rows
filtered_e_cig_data.head()

,_AGEG5YR,ALCDAY4,AVEDRNK4,BLIND,_BMI5,_BMI5CAT,CHECKUP1,CHILDREN,CVDCRHD4,DEAF,...,SDLONELY,SMOKE100,SMOKDAY2,_SMOKER3,SSBSUGR2,SSBFRUT3,STOPSMK2,_TOTINDA,USENOW3,_CURECI3
0,12,888.0,NaN,2.0,2249.0,2.0,1.0,88.0,2.0,2.0,...,5.0,2.0,NaN,4,NaN,NaN,NaN,1,3.0,1
1,13,888.0,NaN,2.0,2583.0,3.0,1.0,88.0,1.0,2.0,...,5.0,1.0,3.0,3,NaN,NaN,NaN,1,3.0,1
2,8,230.0,2.0,2.0,2253.0,2.0,4.0,88.0,2.0,2.0,...,5.0,1.0,1.0,1,NaN,NaN,2.0,1,3.0,1
3,13,888.0,NaN,2.0,2509.0,3.0,1.0,88.0,2.0,1.0,...,5.0,2.0,NaN,4,NaN,NaN,NaN,1,3.0,1
4,6,888.0,NaN,2.0,1977.0,2.0,1.0,88.0,2.0,1.0,...,1.0,2.0,NaN,4,NaN,NaN,NaN,2,3.0,1

In [38]:
filtered_e_cig_data.columns

Index(['_AGEG5YR', 'ALCDAY4', 'AVEDRNK4', 'BLIND', '_BMI5', '_BMI5CAT',
       'CHECKUP1', 'CHILDREN', 'CVDCRHD4', 'DEAF', 'DECIDE', '_DENVST3',
       'DIABETE4', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'ECIGNOW3', 'EDUCA',
       'EMTSUPRT', 'EXERANY2', 'GENHLTH', '_HLTHPL2', 'INCOME3', 'LASTSMK2',
       'LCSSCNCR', '_LCSAGE', '_LCSCTSN', 'LCSLAST_', 'LCSNUMC_', '_LCSYSMK',
       '_LCSSMKG', '_LCSYQTS', 'LSATISFY', 'MARIJAN1', 'MARITAL', 'MEDCOST1',
       'MENTCIGS', 'MENTECIG', '_MENT14D', 'MENTHLTH', '_PACKDAY', '_PACKYRS',
       '_PHYS14D', 'PHYSHLTH', 'POORHLTH', 'PREDIAB2', '_RACE', '_RFBMI5',
       '_RFHLTH', '_RFSMOK3', 'SEXVAR', 'SDHBILLS', 'SDLONELY', 'SMOKE100',
       'SMOKDAY2', '_SMOKER3', 'SSBSUGR2', 'SSBFRUT3', 'STOPSMK2', '_TOTINDA',
       'USENOW3', '_CURECI3'],
      dtype='object')

In [39]:
# Check dimensions of new dataset
filtered_e_cig_data.shape

(457670, 62)

In [43]:
# Export new dataset to a CSV file called initial_variables, which will be located in the data folder of the Repo
# index = False removes index field
filtered_e_cig_data.to_csv('../data/initial_variables.csv', index = False)