In [1]:
#import necessary packages
import pandas as pd
import numpy as np
import openpyxl

In [2]:
#read in data file
data = pd.read_csv('initial_variables.csv')

In [3]:
#get a quick view of the data
data.head()

,_AGEG5YR,ALCDAY4,AVEDRNK4,BLIND,_BMI5,_BMI5CAT,CHECKUP1,CHILDREN,CVDCRHD4,DIABETE4,...,SDLONELY,SMOKE100,SMOKDAY2,_SMOKER3,SSBSUGR2,SSBFRUT3,STOPSMK2,_TOTINDA,USENOW3,_CURECI3
0,12,888.0,NaN,2.0,2249.0,2.0,1.0,88.0,2.0,3.0,...,5.0,2.0,NaN,4,NaN,NaN,NaN,1,3.0,1
1,13,888.0,NaN,2.0,2583.0,3.0,1.0,88.0,1.0,3.0,...,5.0,1.0,3.0,3,NaN,NaN,NaN,1,3.0,1
2,8,230.0,2.0,2.0,2253.0,2.0,4.0,88.0,2.0,3.0,...,5.0,1.0,1.0,1,NaN,NaN,2.0,1,3.0,1
3,13,888.0,NaN,2.0,2509.0,3.0,1.0,88.0,2.0,3.0,...,5.0,2.0,NaN,4,NaN,NaN,NaN,1,3.0,1
4,6,888.0,NaN,2.0,1977.0,2.0,1.0,88.0,2.0,3.0,...,1.0,2.0,NaN,4,NaN,NaN,NaN,2,3.0,1

In [4]:
print(data.columns.tolist())

['_AGEG5YR', 'ALCDAY4', 'AVEDRNK4', 'BLIND', '_BMI5', '_BMI5CAT', 'CHECKUP1', 'CHILDREN', 'CVDCRHD4', 'DIABETE4', 'DEAF', 'DECIDE', '_DENVST3', 'DIABETE4.1', 'DIFFALON', 'DIFFDRES', 'DIFFWALK', 'ECIGNOW3', 'EDUCA', 'EMTSUPRT', 'EXERANY2', 'GENHLTH', '_HLTHPL2', 'INCOME3', 'LASTSMK2', 'LCSSCNCR', '_LCSAGE', '_LCSCTSN', 'LCSLAST_', 'LCSNUMC_', '_LCSYSMK', '_LCSSMKG', '_LCSYQTS', 'LSATISFY', 'MARIJAN1', 'MARITAL', 'MEDCOST1', 'MENTCIGS', 'MENTECIG', '_MENT14D', 'MENTHLTH', '_PACKDAY', '_PACKYRS', '_PHYS14D', 'PHYSHLTH', 'POORHLTH', 'PREDIAB2', '_RACE', '_RFBMI5', '_RFHLTH', '_RFSMOK3', 'SEXVAR', 'SDHBILLS', 'SDLONELY', 'SMOKE100', 'SMOKDAY2', '_SMOKER3', 'SSBSUGR2', 'SSBFRUT3', 'STOPSMK2', '_TOTINDA', 'USENOW3', '_CURECI3']

In [5]:
#remove columns deemed unnecessary
data=data.drop(columns=["_BMI5CAT","CVDCRHD4","ECIGNOW3","_LCSAGE","_LCSCTSN","LCSLAST_","LCSNUMC_","_LCSYSMK",
                       "_LCSSMKG","_LCSYQTS","MENTCIGS","MENTECIG","_PACKDAY","_PACKYRS","_RFBMI5",
                       "_RFSMOK3","SMOKE100","SMOKDAY2","_SMOKER3","STOPSMK2","_TOTINDA", "LASTSMK2","MENTHLTH",
                       "PHYSHLTH"])

In [6]:
#Redefine variable as binary
data["SDHBILLS"]=data["SDHBILLS"].replace(2,0)
data["SDHBILLS"]=data["SDHBILLS"].replace(7,np.nan)
data["SDHBILLS"]=data["SDHBILLS"].replace(9,np.nan)
data=data.rename(columns={"SDHBILLS":"High_Financial_Stress_Burden"})
data['High_Financial_Stress_Burden']=pd.Categorical(data.High_Financial_Stress_Burden)

In [7]:
#Redefine variable as binary
data["LCSSCNCR"]=data["LCSSCNCR"].replace(2,0)
data["LCSSCNCR"]=data["LCSSCNCR"].replace(7,np.nan)
data["LCSSCNCR"]=data["LCSSCNCR"].replace(9,np.nan)
data=data.rename(columns={"LCSSCNCR":"Lung_Cancer_Suspected_Risk"})
data['Lung_Cancer_Suspected_Risk']=pd.Categorical(data.Lung_Cancer_Suspected_Risk)

In [8]:
#Recategorize into better groups
conditions = [
    (data["SEXVAR"] == 1),
    (data["SEXVAR"] == 2)
]
choices = ["Male", "Female"]

data["Sex"] = np.select(conditions, choices, default="Unknown")
data['Sex']=pd.Categorical(data.Sex)

In [9]:
#Create disability variable

data["DEAF"]=data["DEAF"].replace(2,0)
data["DEAF"]=data["DEAF"].replace(7,np.nan)
data["DEAF"]=data["DEAF"].replace(9,np.nan)
data["BLIND"]=data["BLIND"].replace(2,0)
data["BLIND"]=data["BLIND"].replace(7,np.nan)
data["BLIND"]=data["BLIND"].replace(9,np.nan)
data["DECIDE"]=data["DECIDE"].replace(2,0)
data["DECIDE"]=data["DECIDE"].replace(7,np.nan)
data["DECIDE"]=data["DECIDE"].replace(9,np.nan)
data["DIFFWALK"]=data["DIFFWALK"].replace(2,0)
data["DIFFWALK"]=data["DIFFWALK"].replace(7,np.nan)
data["DIFFWALK"]=data["DIFFWALK"].replace(9,np.nan)
data["DIFFDRES"]=data["DIFFDRES"].replace(2,0)
data["DIFFDRES"]=data["DIFFDRES"].replace(7,np.nan)
data["DIFFDRES"]=data["DIFFDRES"].replace(9,np.nan)
data["DIFFALON"]=data["DIFFALON"].replace(2,0)
data["DIFFALON"]=data["DIFFALON"].replace(7,np.nan)
data["DIFFALON"]=data["DIFFALON"].replace(9,np.nan)

conditions = [
    (data['DEAF'] == 1) | (data['BLIND'] == 1) | (data['DECIDE'] == 1) | (data['DIFFWALK'] == 1)
    | (data['DIFFDRES'] == 1) | (data['DIFFALON'] == 1),
    (data['DEAF'] == 0) & (data['BLIND'] == 0) & (data['DECIDE'] == 0) & (data['DIFFWALK'] == 0)
    & (data['DIFFDRES'] == 0) & (data['DIFFALON'] == 0),
]
choices = [1,0]
data['Has_Disability'] = np.select(conditions, choices, default=np.nan)
data['Has_Disability']=pd.Categorical(data.Has_Disability)

In [10]:
#create pre or diabete variable

data["PREDIAB2"]=data["PREDIAB2"].replace(2,1)
data["PREDIAB2"]=data["PREDIAB2"].replace(3,0)
data["PREDIAB2"]=data["PREDIAB2"].replace(7,np.nan)
data["PREDIAB2"]=data["PREDIAB2"].replace(9,np.nan)
data["DIABETE4"]=data["DIABETE4"].replace(2,1)
data["DIABETE4"]=data["DIABETE4"].replace(4,1)
data["DIABETE4"]=data["DIABETE4"].replace(3,0)
data["DIABETE4"]=data["DIABETE4"].replace(7,np.nan)
data["DIABETE4"]=data["DIABETE4"].replace(9,np.nan)

#Recategorize into better groups
conditions = [
    (data["PREDIAB2"] == 1) |  (data["DIABETE4"] == 1),
    (data["PREDIAB2"] == 0) &  (data["DIABETE4"] == 0),
]
choices = [1,0]

data['Diabetic_History'] = np.select(conditions, choices, default=np.nan)
data['Diabetic_History']=pd.Categorical(data.Diabetic_History)

In [11]:
#Recategorize into 4 groups + unknown
conditions = [
    (data['_MENT14D'] == 1),
    (data['_MENT14D'] == 2),
    (data['_MENT14D'] == 3),
    (data['_MENT14D'] == 9),
]
choices = ['0_Days', '1-13_Days', '14+_Days', "Unknown"]

data['Days_Poor_Mental_Health'] = np.select(conditions, choices, default='Unknown')
data['Days_Poor_Mental_Health']=pd.Categorical(data.Days_Poor_Mental_Health)

In [12]:
#Recategorize into 3 groups + unknown
conditions = [
    (data['_AGEG5YR'] < 5),
    (data['_AGEG5YR'] >= 5) & (data['_AGEG5YR'] < 9),
    (data['_AGEG5YR'] >= 9) & (data['_AGEG5YR'] < 14),
    (data['_AGEG5YR'] == 14)
]
choices = ['Young_Adult', 'Middle_Aged', 'Elderly', "Unknown"]

data['Age_Category'] = np.select(conditions, choices, default='Unknown')
data['Age_Category']=pd.Categorical(data.Age_Category)

In [13]:
#Redefine target variable as binary
data['_CURECI3']=pd.to_numeric(data._CURECI3)
conditions = [
    (data["_CURECI3"] == 1),
    (data["_CURECI3"] == 2),
    (data["_CURECI3"] == 9)
]
choices = [0, 1, np.nan]

data["E_Cig_User"] = np.select(conditions, choices, default=np.nan)
data['E_Cig_User']=pd.Categorical(data.E_Cig_User)

In [14]:
#Rename column to better name and devide by 100 to get into more realistic form
data=data.rename(columns={"_BMI5":"BMI"})
data["BMI"]=data["BMI"]/100

In [15]:
#Recategorize into better groups
conditions = [
    (data["USENOW3"] == 1),
    (data["USENOW3"] == 2),
    (data["USENOW3"] == 3),
    (data["USENOW3"] == 7) | (data["USENOW3"] == 9)
]
choices = ["Every Day", "Some days", "Not at all", "Unknown"]

data["Other_Tobacco_Usage"] = np.select(conditions, choices, default="Unknown")
data['Other_Tobacco_Usage']=pd.Categorical(data.Other_Tobacco_Usage)

In [16]:
#Recategorize into better groups
conditions = [
    (data["SEXVAR"] == 1),
    (data["SEXVAR"] == 2)
]
choices = ["Male", "Female"]

data["Sex"] = np.select(conditions, choices, default="Unknown")
data['Sex']=pd.Categorical(data.Sex)

In [17]:
#Recategorize into better groups
conditions = [
    (data["_RACE"] == 1),
    (data["_RACE"] == 2),
    (data["_RACE"] == 3),
    (data["_RACE"] == 4),
    (data["_RACE"] == 5),
    (data["_RACE"] == 6),
    (data["_RACE"] == 7),
    (data["_RACE"] == 8),
    (data["_RACE"] == 9),
]
choices = ["White", "Black", "American Indian or Alaskan Native", "Asian",
           "Native Hawaiian or other Pacific Islander", "Other Race", "Multiracial",
           "Hispanic", "Unknown"]

data["Race"] = np.select(conditions, choices, default="Unknown")
data['Race']=pd.Categorical(data.Race)

In [18]:
#Make these variable observations unknown since this is a continuous variable. Rename to a better name
conditions = [
    (data["ALCDAY4"] == 100),
    (data["ALCDAY4"] > 100) & (data["ALCDAY4"] <= 107),
    (data["ALCDAY4"] > 200) & (data["ALCDAY4"] <= 240),
    (data["ALCDAY4"] == 888),
    (data["ALCDAY4"] == 777) | (data["ALCDAY4"] == 999)
]
choices = [data["ALCDAY4"]-100, data["ALCDAY4"]-100, data["ALCDAY4"]-200, 0, np.nan]

data["ALCDAY4"] = np.select(conditions, choices, default= np.nan)

data["AVEDRNK4"]=data["AVEDRNK4"].replace(88,0)
data["AVEDRNK4"]=data["AVEDRNK4"].replace(77,np.nan)
data["AVEDRNK4"]=data["AVEDRNK4"].replace(99,np.nan)

data["Total_Drinks_30_days"]=data["AVEDRNK4"]*data["ALCDAY4"]
#data=data.rename(columns={"AVEDRNK4":"Average_Number_of_Drinks_30_Days"})

In [19]:
#Recategorize into better groups
conditions = [
    (data["CHECKUP1"] == 1),
    (data["CHECKUP1"] == 2),
    (data["CHECKUP1"] == 3),
    (data["CHECKUP1"] == 4),
    (data["CHECKUP1"] == 7),
    (data["CHECKUP1"] == 8),
    (data["CHECKUP1"] == 29)
]
choices = ["Within_the_last_year", "Within_the_past_two_years", "Within_the_past_five_years", "Five_or_more_years_ago",
          "Unknown", "Never", "Unknown"]

data["Time_Since_Last_Check_Up"] = np.select(conditions, choices, default="Unknown")
data['Time_Since_Last_Check_Up']=pd.Categorical(data.Time_Since_Last_Check_Up)

In [20]:
#Make these variable observations unknown since this is a continuous variable. Rename to a better name
data["CHILDREN"]=data["CHILDREN"].replace(88,0)
data["CHILDREN"]=data["CHILDREN"].replace(99,np.nan)
data=data.rename(columns={"CHILDREN":"Number_of_Children"})

In [21]:
#Redefine variable as binary
data["_DENVST3"]=data["_DENVST3"].replace(2,0)
data["_DENVST3"]=data["_DENVST3"].replace(9,np.nan)
data=data.rename(columns={"_DENVST3":"Dentist_Visit_Last_Year"})

In [22]:
#Recategorize into better groups
conditions = [
    (data["EXERANY2"] == 1),
    (data["EXERANY2"] == 2),
    (data["EXERANY2"] == 7),
    (data["EXERANY2"] == 9)
]
choices = [1, 0, np.nan, np.nan]

data["Exercise_Outside_Work_Past_Month"] = np.select(conditions, choices, default=np.nan)

In [23]:
#Redefine variable as binary
data["_HLTHPL2"]=data["_HLTHPL2"].replace(2,0)
data["_HLTHPL2"]=data["_HLTHPL2"].replace(9,np.nan)
data=data.rename(columns={"_HLTHPL2":"Health_Insurance"})

In [24]:
#Make these variables unknown since this is a continuous variable. Rename to a better name
data["MARIJAN1"]=data["MARIJAN1"].replace(88,0)
data["MARIJAN1"]=data["MARIJAN1"].replace(77,np.nan)
data["MARIJAN1"]=data["MARIJAN1"].replace(99,np.nan)
data=data.rename(columns={"MARIJAN1":"Marijuana_Use_30_Days"})

In [25]:
#Make these variable observations unknown since this is a continuous variable. Rename to a better name
data["MEDCOST1"]=data["MEDCOST1"].replace(2,0)
data["MEDCOST1"]=data["MEDCOST1"].replace(7,np.nan)
data["MEDCOST1"]=data["MEDCOST1"].replace(9,np.nan)
data=data.rename(columns={"MEDCOST1":"Medical_Visit_Missed_Due_to_Cost"})

In [26]:
#Recategorize into better groups
conditions = [
    (data["SDLONELY"] == 1),
    (data["SDLONELY"] == 2),
    (data["SDLONELY"] == 3),
    (data["SDLONELY"] == 4),
    (data["SDLONELY"] == 5),
    (data["SDLONELY"] == 7),
    (data["SDLONELY"] == 9)
]
choices = ["Always", "Usually", "Sometimes", "Rarely", "Never", "Unknown", "Unknown"]

data["Loneliness"] = np.select(conditions, choices, default= "Unknown")

In [27]:
#Recategorize into better groups
conditions = [
    (data["_RFHLTH"] == 1),
    (data["_RFHLTH"] == 2),
    (data["_RFHLTH"] == 9),
]
choices = ["Good_or_Better_Health", "Fair_or_Poor_Health", "Unknown"]

data["Health_Rating"] = np.select(conditions, choices, default= "Unknown")

In [28]:
#Recategorize into better groups
conditions = [
    (data["INCOME3"] == 1),
    (data["INCOME3"] == 2),
    (data["INCOME3"] == 3),
    (data["INCOME3"] == 4),
    (data["INCOME3"] == 5),
    (data["INCOME3"] == 6),
    (data["INCOME3"] == 7),
    (data["INCOME3"] == 8),
    (data["INCOME3"] == 9),
    (data["INCOME3"] == 10),
    (data["INCOME3"] == 11),
    (data["INCOME3"] == 77),
    (data["INCOME3"] == 99)
]
choices = ["Less_than_$10,000", "Less_than_$15,000", "Less_than_$20,000",
          "Less_than_$25,000", "Less_than_$35,000", "Less_than_$50,000",
          "Less_than_$75,000", "Less_than_$100,000", "Less_than_$150,000",
          "Less_than_$200,000", "$200,000+", "Unknown", "Unknown"]

data["Annual_Income"] = np.select(conditions, choices, default= "Unknown")

In [29]:
#Recategorize into better groups
conditions = [
    (data["_PHYS14D"] == 1),
    (data["_PHYS14D"] == 2),
    (data["_PHYS14D"] == 3),
    (data["_PHYS14D"] == 9)
]
choices = ["0_Days", "1-13_Days", "14+_Days", "Unknown"]

data["Days_Poor_Physical_Health"] = np.select(conditions, choices, default= "Unknown")

In [30]:
#Recategorize into better groups
conditions = [
    (data["EDUCA"] == 1),
    (data["EDUCA"] == 2),
    (data["EDUCA"] == 3),
    (data["EDUCA"] == 4),
    (data["EDUCA"] == 5),
    (data["EDUCA"] == 6),
    (data["EDUCA"] == 9)
]
choices = ["Never_attended_school_or_only_Kindergarten", "Grades_1-8_(elementary)", 
          "Grades_9-11_(some_high_school)", "Grade_12_or_GED_(high_school_graduate",
          "College_1-3_years_(some_college_or_technical_school", "College_4_years_or_more_(college_graduate)",
          "Unknown"]

data["Education"] = np.select(conditions, choices, default= "Unknown")

In [31]:
#Recategorize into better groups
conditions = [
    (data["EMTSUPRT"] == 1),
    (data["EMTSUPRT"] == 2),
    (data["EMTSUPRT"] == 3),
    (data["EMTSUPRT"] == 4),
    (data["EMTSUPRT"] == 5),
    (data["EMTSUPRT"] == 7),
    (data["EMTSUPRT"] == 9)
]
choices = ["Always","Usually","Sometimes","Rarely","Never", "Unknown","Unknown"]

data["Social_Emotional_Support"] = np.select(conditions, choices, default= "Unknown")

In [32]:
#Recategorize into better groups
conditions = [
    (data["GENHLTH"] == 1),
    (data["GENHLTH"] == 2),
    (data["GENHLTH"] == 3),
    (data["GENHLTH"] == 4),
    (data["GENHLTH"] == 5),
    (data["GENHLTH"] == 7),
    (data["GENHLTH"] == 9)
]
choices = ["Excellent", "Very_good", "Good", "Fair", "Poor", "Unknown","Unknown"]

data["General_Health_Personal_Rating"] = np.select(conditions, choices, default= "Unknown")

In [33]:
#Recategorize into better groups
conditions = [
    (data["LSATISFY"] == 1),
    (data["LSATISFY"] == 2),
    (data["LSATISFY"] == 3),
    (data["LSATISFY"] == 4),
    (data["LSATISFY"] == 7),
    (data["LSATISFY"] == 9)
]
choices = ["Very_satisfied", "Satisfied", "Dissatisfied", "Very_dissatified", "Unknown", "Unknown"]

data["Life_Satisfaction"] = np.select(conditions, choices, default= "Unknown")

In [34]:
#Recategorize into better groups
conditions = [
    (data["MARITAL"] == 1),
    (data["MARITAL"] == 2),
    (data["MARITAL"] == 3),
    (data["MARITAL"] == 4),
    (data["MARITAL"] == 5),
    (data["MARITAL"] == 6),
    (data["MARITAL"] == 9)
]
choices = ["Married", "Divorced", "Widowed", "Separated", "Never_Married", "Member_of_unmarried_couple",
          "Unknown"]

data["Marital_Status"] = np.select(conditions, choices, default= "Unknown")

In [35]:
#Split initial variable into 3 variables: day, week, and month
conditions = [
    (data["SSBSUGR2"] < 200)
]
choices = [data["SSBSUGR2"]-100]

data["Sugar_Soda_Drinks_Per_Day"] = np.select(conditions, choices, default= np.nan)

In [36]:
#Split initial variable into 3 variables: day, week, and month
conditions = [
    (data["SSBSUGR2"] < 300)
]
choices = [data["SSBSUGR2"]-200]

data["Sugar_Soda_Drinks_Per_Week"] = np.select(conditions, choices, default= np.nan)

In [37]:
#Split initial variable into 3 variables: day, week, and month
conditions = [
    (data["SSBSUGR2"] < 400)
]
choices = [data["SSBSUGR2"]-300]

data["Sugar_Soda_Drinks_Per_Month"] = np.select(conditions, choices, default= np.nan)

In [38]:
#Split initial variable into 3 variables: day, week, and month
conditions = [
    (data["SSBFRUT3"] < 200)
]
choices = [data["SSBFRUT3"]-100]

data["Non_Soda_Sugar_Drinks_Per_Day"] = np.select(conditions, choices, default= np.nan)

In [39]:
#Split initial variable into 3 variables: day, week, and month
conditions = [
    (data["SSBFRUT3"] < 300) & (data['SSBFRUT3'] > 200)
]
choices = [data["SSBFRUT3"]-200]

data["Non_Soda_Sugar_Drinks_Per_Week"] = np.select(conditions, choices, default= np.nan)

In [40]:
#Split initial variable into 3 variables: day, week, and month
conditions = [
    (data["SSBFRUT3"] < 400) & (data['SSBFRUT3'] > 300)
]
choices = [data["SSBFRUT3"]-300]

data["Non_Soda_Sugar_Drinks_Per_Month"] = np.select(conditions, choices, default= np.nan)

In [41]:
#Make these variable observations unknown since this is a continuous variable. Rename to a better name
data["POORHLTH"]=data["POORHLTH"].replace(88,0)
data["POORHLTH"]=data["POORHLTH"].replace(77,np.nan)
data["POORHLTH"]=data["POORHLTH"].replace(99,np.nan)
data=data.rename(columns={"POORHLTH":"Number_of_Days_Last_Month_Poor_Health"})

In [42]:
#Dropping columns that are unnecessary since new variables have been created
data=data.drop(columns=['_AGEG5YR','_CURECI3','USENOW3','SEXVAR',"_RACE","CHECKUP1","EXERANY2",
                       "SDLONELY","_RFHLTH","PREDIAB2","INCOME3","_PHYS14D","EDUCA","EMTSUPRT",
                       "GENHLTH", "LSATISFY", "MARITAL","SSBSUGR2","SSBFRUT3", "_MENT14D",
                       "AVEDRNK4","ALCDAY4", "DEAF", "DECIDE","BLIND","DIFFWALK","DIFFDRES","DIFFALON",
                       "PREDIAB2","DIABETE4","DIABETE4.1"])

In [43]:
#Review data one last time
data.head()

,BMI,Number_of_Children,Dentist_Visit_Last_Year,Health_Insurance,Lung_Cancer_Suspected_Risk,Marijuana_Use_30_Days,Medical_Visit_Missed_Due_to_Cost,Number_of_Days_Last_Month_Poor_Health,High_Financial_Stress_Burden,Sex,...,Social_Emotional_Support,General_Health_Personal_Rating,Life_Satisfaction,Marital_Status,Sugar_Soda_Drinks_Per_Day,Sugar_Soda_Drinks_Per_Week,Sugar_Soda_Drinks_Per_Month,Non_Soda_Sugar_Drinks_Per_Day,Non_Soda_Sugar_Drinks_Per_Week,Non_Soda_Sugar_Drinks_Per_Month
0,22.49,0.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,Female,...,Always,Good,Very_satisfied,Widowed,NaN,NaN,NaN,NaN,NaN,NaN
1,25.83,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
2,22.53,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,Male,...,Usually,Very_good,Very_satisfied,Member_of_unmarried_couple,NaN,NaN,NaN,NaN,NaN,NaN
3,25.09,0.0,1.0,1.0,NaN,NaN,0.0,NaN,0.0,Male,...,Always,Excellent,Very_satisfied,Married,NaN,NaN,NaN,NaN,NaN,NaN
4,19.77,0.0,1.0,1.0,0.0,NaN,0.0,NaN,0.0,Male,...,Rarely,Good,Satisfied,Never_Married,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
#Changing data type to categorical for necessary variables
data['Marital_Status']=pd.Categorical(data.Marital_Status)
data['Life_Satisfaction']=pd.Categorical(data.Life_Satisfaction)
data['General_Health_Personal_Rating']=pd.Categorical(data.General_Health_Personal_Rating)
data['Social_Emotional_Support']=pd.Categorical(data.Social_Emotional_Support)
data['Education']=pd.Categorical(data.Education)
data['Days_Poor_Physical_Health']=pd.Categorical(data.Days_Poor_Physical_Health)
data['Annual_Income']=pd.Categorical(data.Annual_Income)
data['Health_Rating']=pd.Categorical(data.Health_Rating)
data['Loneliness']=pd.Categorical(data.Loneliness)
data['Exercise_Outside_Work_Past_Month']=pd.Categorical(data.Exercise_Outside_Work_Past_Month)
data['Medical_Visit_Missed_Due_to_Cost']=pd.Categorical(data.Medical_Visit_Missed_Due_to_Cost)
data['Health_Insurance']=pd.Categorical(data.Health_Insurance)
data['Dentist_Visit_Last_Year']=pd.Categorical(data.Dentist_Visit_Last_Year)

In [45]:
#checking data types
data.dtypes

BMI                                       float64
Number_of_Children                        float64
Dentist_Visit_Last_Year                  category
Health_Insurance                         category
Lung_Cancer_Suspected_Risk               category
Marijuana_Use_30_Days                     float64
Medical_Visit_Missed_Due_to_Cost         category
Number_of_Days_Last_Month_Poor_Health     float64
High_Financial_Stress_Burden             category
Sex                                      category
Has_Disability                           category
Diabetic_History                         category
Days_Poor_Mental_Health                  category
Age_Category                             category
E_Cig_User                               category
Other_Tobacco_Usage                      category
Race                                     category
Total_Drinks_30_days                      float64
Time_Since_Last_Check_Up                 category
Exercise_Outside_Work_Past_Month         category
Loneliness                               category
Health_Rating                            category
Annual_Income                            category
Days_Poor_Physical_Health                category
Education                                category
Social_Emotional_Support                 category
General_Health_Personal_Rating           category
Life_Satisfaction                        category
Marital_Status                           category
Sugar_Soda_Drinks_Per_Day                 float64
Sugar_Soda_Drinks_Per_Week                float64
Sugar_Soda_Drinks_Per_Month               float64
Non_Soda_Sugar_Drinks_Per_Day             float64
Non_Soda_Sugar_Drinks_Per_Week            float64
Non_Soda_Sugar_Drinks_Per_Month           float64
dtype: object

In [46]:
#Output as .CSV
#Currently commented out since not always necessary to run
data.to_csv("cleaned_data.csv")